version: '3'
services:
  blueprintbug:
    container_name: blueprintbug
    build: ./
    volumes:
      - C:\blueprintbug\blueprintbug\:/usr/src/app
    command: [ 'gunicorn', '-c', 'gunicorn.conf.py', "app:create_app()", '--reload' ]
    ports:
      - "8080:8080"